name: Label Issues

on:
 issues:
  types:
   -opened
   -reopened

jobs:
 label_issues:
  runs-on: any
  permissions:
   issues: write
  steps:
   -uses: actions/github-script@v6
   with: null
   script: |
    github.rest.issues.addLabels({
    issue_number: context.issue_number,
    owner: context.repo.owner,
    repo: context.repo.repo
    label: ["Beginner"]  
  })
    
    
   
   
  
   
 
  



